// frontend/src/routes/legal/privacy/+page.svelte
﻿<svelte:head>
	<title>Privacy Policy · GitPier</title>
	<meta name="description" content="Simple, general privacy policy for GitPier." />
</svelte:head>

<div class="bg-background min-h-screen py-12 px-4">
	<div class="mx-auto max-w-3xl">
		<header class="mb-10">
			<p class="text-xs font-semibold uppercase tracking-widest text-primary mb-2">Legal</p>
			<h1 class="text-3xl font-bold tracking-tight text-foreground">Privacy Policy</h1>
			<p class="mt-2 text-sm text-muted-foreground">Last updated: <time datetime="2026-05-23">May 23, 2026</time></p>
		</header>

		<div
			class="prose prose-sm max-w-none text-foreground
			[&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-foreground [&_h2]:mt-8 [&_h2]:mb-3
			[&_p]:text-sm [&_p]:text-muted-foreground [&_p]:leading-relaxed [&_p]:mb-3
			[&_ul]:text-sm [&_ul]:text-muted-foreground [&_ul]:pl-5 [&_ul]:mb-3 [&_ul]:space-y-1 [&_ul>li]:list-disc
			[&_a]:text-primary [&_a]:underline [&_a]:underline-offset-2 [&_a:hover]:text-primary/80"
		>
			<p>This Privacy Policy explains in simple terms what data we collect, why we collect it, and your choices when using GitPier.</p>

			<h2>What We Collect</h2>
			<ul>
				<li>Account information such as username, email address, and encrypted password.</li>
				<li>Content you create, including repositories, commits, issues, pull requests, comments, and packages.</li>
				<li>Basic technical data such as IP address, browser type, and access logs for security and operations.</li>
			</ul>

			<h2>How We Use Data</h2>
			<ul>
				<li>To provide and maintain the service.</li>
				<li>To secure accounts and prevent abuse.</li>
				<li>To improve stability and troubleshoot problems.</li>
				<li>To communicate important service updates.</li>
			</ul>

			<h2>Data Sharing</h2>
			<p>We do not sell your personal data. We only share data when required to operate the service, comply with the law, or protect users and the platform.</p>

			<h2>Data Retention</h2>
			<p>We keep data only as long as needed for service operation, legal requirements, and security purposes. Public repository data may remain visible until removed.</p>

			<h2>Your Choices</h2>
			<ul>
				<li>You can update profile information from account settings.</li>
				<li>You can request account deletion.</li>
				<li>You can contact us for privacy-related requests.</li>
			</ul>

			<h2>Contact</h2>
			<p>For privacy questions, contact: <a href="mailto:privacy@example.com">privacy@example.com</a></p>

			<h2>Updates</h2>
			<p>We may update this policy from time to time. Continued use of GitPier means you accept the latest version.</p>
		</div>
	</div>
</div>

// apps/website/app/routes/legal/privacy.tsx
import type { Route } from './+types/privacy';

export function meta() {
  return [
    { title: 'Privacy Policy · GitPier' },
    { name: 'description', content: 'Privacy policy for the GitPier alpha website.' },
  ];
}

export default function PrivacyPage() {
  return (
    <section className="mx-auto mt-12 max-w-3xl px-4 py-24 text-foreground">
      <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: <time dateTime="2026-05-31">May 31, 2026</time>
      </p>

      <div className="mt-8 space-y-5 text-sm text-muted-foreground leading-relaxed">
        <p>GitPier is currently in an alpha stage. This policy explains what data is processed when you use this website.</p>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Data we collect now</h2>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>Basic technical logs (for example, IP address and browser details) for security and abuse prevention.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">How we use it</h2>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>To operate and secure this website.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Cookies and consent</h2>
          <p>We only enable analytics after you accept the cookie banner.</p>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li><code>_trk_uid</code>: visitor identifier used for analytics visit tracking (stored for up to 365 days).</li>
            <li><code>_trk_ses</code>: session identifier used to group page views in a single session (stored for about 30 minutes and refreshed while active).</li>
          </ul>
          <p className="mt-2">These cookies are first-party analytics cookies used by GitPier for traffic measurement.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Sharing</h2>
          <p>We do not sell your personal data. We only share data when required by law or to run the service.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Retention</h2>
          <p>We retain technical logs only as long as needed for security, abuse prevention, and operational reliability.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Contact</h2>
          <p>For privacy requests, contact <a className="text-brand underline underline-offset-2" href="mailto:privacy@gitpier.com">privacy@gitpier.com</a>.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Changes</h2>
          <p>We may update this policy as GitPier evolves. The latest version will always be posted here.</p>
        </div>
      </div>
    </section>
  );
}
