// frontend/src/routes/legal/terms/+page.svelte
﻿<svelte:head>
	<title>Terms of Service · GitPier</title>
	<meta name="description" content="Simple, general terms of service for GitPier." />
</svelte:head>

<div class="bg-background min-h-screen py-12 px-4">
	<div class="mx-auto max-w-3xl">
		<header class="mb-10">
			<p class="text-xs font-semibold uppercase tracking-widest text-primary mb-2">Legal</p>
			<h1 class="text-3xl font-bold tracking-tight text-foreground">Terms of Service</h1>
			<p class="mt-2 text-sm text-muted-foreground">Last updated: <time datetime="2026-05-23">May 23, 2026</time></p>
		</header>

		<div
			class="prose prose-sm max-w-none text-foreground
			[&_h2]:text-lg [&_h2]:font-semibold [&_h2]:text-foreground [&_h2]:mt-8 [&_h2]:mb-3
			[&_p]:text-sm [&_p]:text-muted-foreground [&_p]:leading-relaxed [&_p]:mb-3
			[&_ul]:text-sm [&_ul]:text-muted-foreground [&_ul]:pl-5 [&_ul]:mb-3 [&_ul]:space-y-1 [&_ul>li]:list-disc
			[&_a]:text-primary [&_a]:underline [&_a]:underline-offset-2 [&_a:hover]:text-primary/80"
		>
			<p>These Terms of Service describe the basic rules for using GitPier. By using the platform, you agree to these terms.</p>

			<h2>Use of Service</h2>
			<ul>
				<li>You must use the service lawfully.</li>
				<li>You are responsible for your account and your content.</li>
				<li>You must not upload malicious, illegal, or abusive content.</li>
			</ul>

			<h2>Your Content</h2>
			<p>You keep ownership of content you upload. You grant us permission to store and display it as needed to operate the service.</p>

			<h2>Accounts</h2>
			<p>We may suspend or remove accounts that violate these terms or harm the platform or other users.</p>

			<h2>Availability</h2>
			<p>The service is provided "as is" and may change, pause, or stop at any time.</p>

			<h2>Liability</h2>
			<p>To the extent permitted by law, we are not liable for indirect damages, data loss, or service interruptions.</p>

			<h2>Changes</h2>
			<p>We may update these terms from time to time. Continued use of GitPier means you accept the latest version.</p>

			<h2>Contact</h2>
			<p>For questions about these terms, contact: <a href="mailto:legal@example.com">legal@example.com</a></p>
		</div>
	</div>
</div>

// apps/website/app/routes/legal/terms.tsx
import type { Route } from './+types/terms';

export function meta() {
  return [
    { title: 'Terms of Service · GitPier' },
    { name: 'description', content: 'Terms for using the GitPier alpha website.' },
  ];
}

export default function TermsPage() {
  return (
    <section className="mx-auto mt-12 max-w-3xl px-4 py-24 text-foreground">
      <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: <time dateTime="2026-05-27">May 27, 2026</time>
      </p>

      <div className="mt-8 space-y-5 text-sm text-muted-foreground leading-relaxed">
        <p>These terms apply to your use of the GitPier alpha website.</p>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Pre-launch status</h2>
          <p>GitPier is not fully launched yet. Features, timelines, and availability may change at any time.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Acceptable use</h2>
          <ul className="mt-2 list-disc pl-5 space-y-1">
            <li>Use this website lawfully.</li>
            <li>Do not attempt to abuse, disrupt, or attack the service.</li>
          </ul>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">No warranty</h2>
          <p>This website is provided &quot;as is&quot; without warranties of any kind.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Limitation of liability</h2>
          <p>To the extent allowed by law, we are not liable for indirect or consequential damages from use of this alpha site.</p>
        </div>

        <div>
          <h2 className="text-lg font-semibold text-foreground">Changes</h2>
          <p>We may update these terms as GitPier develops. Continued use means you accept the latest version.</p>
        </div>
      </div>
    </section>
  );
}
